### ISSUE TITLE
Add mtools to the list of packages installed

### ISSUE THREAD

**Issue by rachlmac** [hawkw/sos-kernel#52]

**Comment by hawkw** [comment]
This is definitely an issue on Manjaro and I assume on other Arch-derived distributions. @phil-opp has added it to the dependencies for his Rust kernel project, so I'm assuming it's necessary on Debian-like Linuces as well?  Looks like the current version of `grub-mkrescue` now requires `mtools` probably?

**Comment by hawkw** [comment]
The lines in question are [line 42](https://github.com/hawkw/sos-kernel/blob/master/scripts/install-env-linux.sh#L42) and [line 59](https://github.com/hawkw/sos-kernel/blob/master/scripts/install-env-linux.sh#L59) in `install-env-linux.sh`. All that should be necessary is adding `mtools` to the list of packages installed, I believe. Would like this confirmed by someone on Ubuntu or a Debian-like, though.

The corresponding [documentation](https://github.com/hawkw/sos-kernel/blob/master/BUILDING.md#installing-build-dependencies) in BUILDING.md should also be updated to add `mtools` as well.

**Comment by phil-opp** [comment]
> @phil-opp has added it to the dependencies for his Rust kernel project, so I'm assuming it's necessary on Debian-like Linuces as well?

It was added to the dependency list in phil-opp/blog_os#213 because it was needed on arch. I don't know if it's required for ubuntu/debian systems.

**Comment by hawkw** [comment]
@phil-opp: 

>  I don't know if it's required for ubuntu/debian systems.

Oh, okay. Hmm. I'd like to hear from someone using a Debian-like OS, then, before we add it to the build dependencies for all Linuces. That's probably its' own issue...
