### ISSUE TITLE
`make env` raises error [OS X Sierra]

### ISSUE THREAD

**Issue by SnailShea** [hawkw/sos-kernel#54]
> install-mac: Adding target linker to /Users/shea/.cargo/config...
> 
> install-env: Installing `xargo`.
> 
> error: Couldn't load Cargo configuration
> 
> Caused by:
>   could not parse TOML configuration in `/Users/shea/.cargo/config`
> 
> Caused by:
>   could not parse input as TOML
> /Users/shea/.cargo/config:1:4-2:1 expected `=`, but found `
> `
> 
> make: *** [env] Error 101

**Comment by SnailShea** [comment]
Issue lies in the installation of `xargo` due to some issue with .cargo/config

Deleted this file manually, ran `cargo install xargo`, and it installed successfully.

`make env` still will not run successfully after this workaround, however, so if it's meant to do anything else, this will not work entirely.

**Comment by hawkw** [comment]
@MxLinux, you said

> `make env` still will not run successfully after this workaround, however, so if it's meant to do anything else, this will not work entirely.

Can you open another issue for any problems you're continuing to have?

**Comment by hawkw** [comment]
@MxLinux, can I get you to post the contents of `/Users/shea/.cargo/config`, ideally before and after you re-installed `xargo`?

**Comment by SnailShea** [comment]
```
[shea] [~/Projects/sos-kernel] cat /Users/shea/.cargo/config 
-e

-e [[target.x86-sos-kernel-gnu]]
linker = "/Users/shea/opt/bin/x86_64-pc-elf-gcc"


[[target.x86-sos-kernel-gnu]]
linker = "/Users/shea/opt/bin/x86_64-pc-elf-gcc"


[[target.x86-sos-kernel-gnu]]
linker = "/Users/shea/opt/bin/x86_64-pc-elf-gcc"


[[target.x86-sos-kernel-gnu]]
linker = "/Users/shea/opt/bin/x86_64-pc-elf-gcc"


[[target.x86-sos-kernel-gnu]]
linker = "/Users/shea/opt/bin/x86_64-pc-elf-gcc"
```

`xargo` is already installed so I can't get the before, sorry.

**Comment by hawkw** [comment]
Oh, jeez, that's definitely not right. It's only supposed to say 

```
[target.x86_64-sos-kernel-gnu]
linker = "/Users/eliza/opt/bin/x86_64-pc-elf-gcc"
```

once. 

It looks like the rogue `-e`s in there and the two sets of brackets around the name of the target, as well as the duplicate keys, are causing syntax errors.

I don't know how those got in there, I must have made a mistake in the [macOS install script](https://github.com/hawkw/sos-kernel/blob/master/scripts/install-env-mac.sh#L121-L122) where it adds the configuration. My bad!
